name: Test

on: pull_request

jobs:
  test:
    strategy:
      matrix:
        go-version: [1.17.x]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Test build
        run: |
          go build -race -v cmd/planet-exporter/main.go
          go build -race -v cmd/planet-federator/main.go

      - name: Unit tests
        run: go test -race -v ./...
